function out_mat = getStateVals(state_mat,PRM_locs,value)
%GETSTATEVALS pull values for PRM locations of matrix of output structures
%for states
% allardlab.com
    %   out_mat =
    %   GETSTATEVALS(state_mat, PRM_locs,value) creates matrix of output
    %   structures from the files in folder that correspond to the
    %   specified states of the given PRM_locs
    %
    %   Inputs:
    %         state_mat: (struct) ix1 structure array containing output
    %                   structures, generated by readInMSBFiles
    %         PRM_locs : array of PRM locations, if 1 then will get the
    %         value at the base (0) for each state
    %         value    : (string) polymer-c code output value to get
    %
    %   Outputs:
    %         out_mat : (mat) ixN matrix containing values for each PRM in
    %         each state, each row is a state, each column is a PRM
    %
    %       Where N= number of PRMs and i= numValidStates
    %   
    %   See also GETOUTPUTCONTROL, GENERATETMTEMPLATE, READINMSBFILES.


nStates=length(state_mat);
nPRMs=length(PRM_locs);

out_mat=zeros(nStates,2*nPRMs);

for i=1:nStates
    val=state_mat(i).(value);
    for j=1:nPRMs
        PRM_loc=PRM_locs(j);
        out_mat(i,j)=val(1,PRM_loc);
        out_mat(i,j+nPRMs)=val(2,PRM_loc);
    end
end

end