function [output_mat, output_cell] = readInMSBFiles(folder, states, PRM_locs)
%READINMSBFILES create matrix of output structures of files corresponding
%to various bound/ unbound states of a formin FH1
% allardlab.com
    %   [output_mat, output_cell] =
    %   READINMSBFILES(folder, states, PRM_locs) creates matrix of output
    %   structures from the files in folder that correspond to the
    %   specified states of the given PRM_locs
    %
    %   Inputs:
    %         folder   : folder containing polymer-c output files
    %         states   : (mat) ixN matrix with matrix with states,
    %                   generated by generateTMtemplate, each row is a state, each
    %                   column is a PRM, the values are: 
    %                               0- unbound
    %                               1- bound
    %                               2- delivered
    %         PRM_locs : array of PRM locations
    %
    %   Outputs:
    %         output_mat : (struct) ix1 structure array containing output
    %         structures 
    %         output_cell : (cell) ix1 cell array containing output
    %         structures, the same as output_mat but in cell form
    %
    %       Where N= number of PRMs and i= numValidStates
    %   
    %   See also GETOUTPUTCONTROL, GENERATETMTEMPLATE, GETSTATEVALS.

nStates=length(states);
nPRMs=length(PRM_locs);

occtexts=cell(nStates,1);

for i=1:nStates
    occtext="";
    for j=1:nPRMs
        if states(i,j)==1 || states(i,j)==2 % if delivered or bound, consider it bound
            occtext=strcat(occtext,num2str(PRM_locs(j)),"_");
        end
    end
    if occtext==""
        occtext="-1_";
    end
    nobound=1;
    for j=1:nPRMs
        if states(i,j+nPRMs)==1 || states(i,j+nPRMs)==2 % if delivered or bound, consider it bound
            nobound=0;
            occtext=strcat(occtext,"_",num2str(PRM_locs(j)));
        end
    end
    if nobound
        occtext=strcat(occtext,"_-1");
    end
    
    occtexts{i}=occtext;
end

files=dir(fullfile(folder,'run.*'));

output_cell=cell(nStates,1);

for i=1:length(files)
    newStr= strsplit(files(i).name,"occupied");
    occtext=newStr{2};

    matchState=cellfun(@(x) isequal(x,occtext),occtexts);

    if any(matchState)
        subfolder=strcat(files(i).folder,"/",files(i).name);
        subfiles=dir(fullfile(subfolder,'output_*.txt'));
        if length(subfiles)>1
            error("multiple output files for %s",files(i).name)
        end
        path = strcat(subfiles(1).folder,"/");
        out_struct= getOutputControl(subfiles(1).name,input_file_path=path);
        output_cell(matchState)={out_struct};
    end
end

output_mat=cell2mat(output_cell);

end